from exceptions.queue_and_db_exception import QueueAndDbException


class CommandRuntimeError(QueueAndDbException):
    pass
